// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH3DafBav-iX7UzKdk6lrrKLJsiEqVYWY',
    appId: '1:550294455119:web:9485cd50de9bd66e093b3a',
    messagingSenderId: '550294455119',
    projectId: 'aaaa-2a7f5',
    authDomain: 'aaaa-2a7f5.firebaseapp.com',
    databaseURL: 'https://aaaa-2a7f5-default-rtdb.firebaseio.com',
    storageBucket: 'aaaa-2a7f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP1UqyGR6tOlvVNcfDYeN06pVGhiMERm4',
    appId: '1:550294455119:android:51b9db7171d2c391093b3a',
    messagingSenderId: '550294455119',
    projectId: 'aaaa-2a7f5',
    databaseURL: 'https://aaaa-2a7f5-default-rtdb.firebaseio.com',
    storageBucket: 'aaaa-2a7f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbjjIVTs70x0IYovkJRjmFPNz3UURsHwg',
    appId: '1:550294455119:ios:d8033dc7ff97f32b093b3a',
    messagingSenderId: '550294455119',
    projectId: 'aaaa-2a7f5',
    databaseURL: 'https://aaaa-2a7f5-default-rtdb.firebaseio.com',
    storageBucket: 'aaaa-2a7f5.firebasestorage.app',
    iosBundleId: 'com.example.halan',
  );
}
